status = [
  "Android Stable",
  "iOS Stable",
  "MacOS Stable",
  "MacOS Nightly",
  "MacOS Stable (Vulkan)",
  "Ubuntu Stable",
  "Ubuntu Nightly",
  "Windows Stable",
  "Windows Nightly",
  "release-build - Linux-64",
  "release-build - Linux-32",
  "release-build - MacOS-64",
  "release-build - Windows-64",
  "release-build - Windows-32"
]

timeout_sec = 18000 # 5 hours
